

###
GET http://localhost:5000/meetups?page=1&limit=20

###
GET http://localhost:5000/meetups

###
GET http://localhost:5000/meetups?title=join

###
GET http://localhost:5000/meetups?title=join&page=1&limit=20
###
GET http://localhost:5000/countries?name=Andorra

###
GET http://localhost:5000/countries?iso2=A

###
GET http://localhost:5000/countries?iso2=AS&page=1&limit=1


###
GET http://localhost:5000/countries?iso2=A&page=1&limit=1
###
GET http://localhost:5000/countries

###
GET http://localhost:5000/countries?page=1&limit=20